

Installation's guide
--------------------
.. toctree::
   :maxdepth: 2
   
   installation_simple_mode
   installation_serverclient_mode

User's Guide
--------------------

.. toctree::
   :maxdepth: 2

   setup_facebook_app		
   setup_twitter_app
   command_line
   facebook_consumer
   command_line_server
   webconsole
   <!-- extending	 -->

   
Additional Notes
----------------

Design notes and legal information are here for the interested:

.. toctree::
   :maxdepth: 2

   license



