

Installation's guide
--------------------
.. toctree::
   :maxdepth: 2
   
   installation_server
   installation_client

User's Guide
--------------------

This part of the documentation is written text and should give you an idea
how to work with SocialBus.

.. toctree::
   :maxdepth: 2

   setup_twitter_app
   command_line_server
   command_line

   
Additional Notes
----------------

Design notes and legal information are here for the interested:

.. toctree::
   :maxdepth: 2

   license



